site_name: Libertad Pantoja's Profile
nav:
  - My profile:
    - Home: index.md
    - Skills:
      - Advanced: advanced.md
      - Intermediate: intermediate.md
      - Novice: novice.md
    - More about me: about.md

theme:
  name: material
  palette:
    primary: black
    accent: indigo
  logo: images/wizeline_isotype.png